people = {
    ###CRYPTO - FOUNDER###
    "Satoshi Nakamoto": ["satoshi", "nakamoto", "satoshi nakamoto"],
    "Vitalik Buterin": ["vitalik", "buterin", "vitalik buterin"],
    "Brock Pierce": ["brock pierce"],
    "Reeve Collins": ["reeve collins"],
    "Craig Sellars": ["craig sellars"],
    "Jed McCaleb": ["jed McCaleb"],
    "Chris Larsen": ["chris Larsen"],
    "Changpeng Zhao": ["cz", "changpeng zhao", "chanpeng"],
    "Anatoly Yakovenko": ["anatoly yakovenko"],
    "Circle": ["circle"],
    "Billy Markus": ["shibetoshi nakamoto", "billy markus", "shibetoshi"],
    "Charles Hoskinson": ["charles hoskinson"],
    "Cardano": ["charles hoskinson"],
    "Justin Sun": ["justin sun"],
    "Sergey Nazarov": ["sergey nazarov"],
    "Steve Ellis": ["steve ellis"],
    "Pavel Durov": ["pavel durov"],
    "Emin Gün Sirer": ["eming gün", "eming gün sirer"],
    "Kevin Sekniqi": ["kevin sekniqui"],
    "Ted Yin": ["ted yin"],
    "Denelle Dixon": ["denelle dixon"],
    "Leemon Baird": ["leemon baird"],
    "Mance Harmon": ["mance harmon"],
    "Zenobia Godschalk": ["zenobia godschalk"],
    "Ryoshi": ["ryoshi"],
    "Mysten Labs": ["mysten labs","mysten"],
    "Evan Cheng": ["evan cheng"],
    "Sam Blackshear": ["sam blackshear"],
    "Adeniyi Abiodun": ["adeniyi abiodun"],
    "George Danezis": ["george danezis"],
    "Gavin Wood": ["gavin wood"],
    "Charlie Lee": ["charlie lee"],
    "Nicolas Kokkalis": ["nicolas kokkalis"],
    "John Patrick Mullin": ["john patrick mullin"],
    "Gracy Chen": ["gracy chen"],
    "Jeff Yan": ["jeff yan"],
    "Iliensinc": ["iliensinc"],
    "Hayden Adams": ["hayden adams"],
    "Joseph Liu": ["joseph liu"],
    "Mo Shaikh": ["mo shaikh"],
    "Avery Ching": ["avery ching"],
    "Illia Polosukhin": ["illia polosukhin"],
    "Zachary Testa": ["zachary testa"],
    "Star Xu": ["star xu"],
    "Stani Kulechov": ["stani kulechov"],
    "Dominic Williams": ["dominic williams"],
    "Pascal Leblanc": ["pascal leblanc"],
    "Nathan Allman": ["nathan allman"],
    "Pinku Suran": ["pinku suran"],
    "Jacob Steeves": ["jacob steeves"],
    "Ala Shaabana": ["ala shaabana"],
    "Jaynti Kanani": ["jaynti kanani"],
    "Sunny Lu": ["sunny lu"],
    "Kris Marszalek": ["kris marszalek"],
    "Rafael Melo": ["rafael melo"],
    "Gary Or": ["gary or"],
    "Bobby Bao": ["bobby bao"],
    "Guy Young": ["guy young"],
    "Yonatan Sompolinsky": ["yonatan sompolinsky"],
    "Mustafa Al-Bassam": ["mustafa al-bassam"],
    "Juan Benet": ["juan benet"],
    "Lin Han": ["lin han"],
    "Jules Urbach": ["jules urbach"],
    "Jae Kwon": ["jae kwon"],
    "Ed Felten": ["ed felten"],
    "Steven Goldfeder": ["steven goldfeder"],
    "Harry Kalodner": ["harry kalodner"],
    "Silvio Micali": ["silvio micali"],
    "Andre Cronje": ["andre cronje"],
    "Meow": ["meow"],
    "Jinglan Wang": ["jinglan wang"],
    "Kevin Ho": ["kevin ho"],
    "Karl Floersch": ["karl floersch"],
    "Johnny Lyu": ["johnny lyu"],
    "Toby Simpson": ["toby simpson"],
    "Humayun Sheikh": ["humayun sheikh"],
    "Thomas Hain": ["thomas hain"],
    "Robbie Ferguson": ["robbie ferguson"],
    "James Ferguson": ["james ferguson"],
    "Alex Connolly": ["alex connolly"],
    "Eric Chen": ["eric chen"],
    "Rushi Manche": ["rushi manche"],
    "Cooper Scanlon": ["cooper scanlon"],
    "Sam Altman": ["sam altman"],
    "Dan Edlebeck": ["dan edlebeck"],
    "Jayendra Jog": ["jayendra jog"],
    "Mitch Liu's": ["mitch liu's"],
    "Eric Schiermeyer": ["eric schiermeyer"],
    "Antoni Trenchev": ["antoni trenchev"],
    "Man Bera": ["man bera"],
    "Amir Haleem": ["amir haleem"],
    "Sky Mavis": ["sky mavis"],
    "TN Lee": ["tn lee"],
    "Alexander Zaidelson": ["alexander zaidelson"],
    "Alex Romanov": ["alex romanov"],
    "Amir Aaronson": ["amir aaronson"],
    "Mark Rydo": ["mark rydo"],


    ###PRESIDENTI FINANCTIAL INSTITUTION###
    "Jerome Powell": ["jerome powell", "powell"],           #FED - Federal Reserve Bank 
    "Christine Lagarde": ["christine lagarde", "lagarde"],  #BCE - Banca Centrale Europea
    "Gary Gensler":["gary gensler","gensler"],              #SEC - Security Exchange Commission
    "François Villeroy de Galhau": ["françois villeroy de galhau", "françois villeroy","villeroy de galhau"], #BRI - Banca dei Reogolamenti Internazionali
    "Kristalina Georgieva": ["kristalina georgieva","kristalina","georgieva"], #FMI - Fondo Monetario Internazionale
    "Ajay Banga":["ajay banga"], #BM - Banca Mondiale
    "Klaas Knot": ["klaas knot"], #FDB - Consiglio per la stabilità finanziaria
    "Josef Ackermann": ["josef ackermann"], #IIF - Istituto della Finanza Internazionale
    "Tharman Shanmugaratnam": ["tharman shanmugaratnam", "shanmugartanam"], # G30 - Gruppo dei trenta
    "Ngozi Okonjo-Iweala": ["ngozi okonjo-iweala","okonjo-iweala"], #OMC - Organizzazione Mondiale del Commercio
    "Masatsugu Asakawa" : ["masatsugu asakawa"], #ADB - Banca Asiatica di Sviluppo
    "Akinwumi A. Adesina": ["akinwumi adesina","akinwumi a. adesina"], #AfDB - Banca Africana di Sviluppo
    "Ilan Goldfajn": ["ilan goldfajn"], #IDB - Banca Interamericana di Sviluppo""
    "Odile Renaud-Basso": ["odile renaud-basso","renaud-basso"],    #BERS - Banca Europea per la Ricostruzione e lo Sviluppo (BERS)


    ###CEO - Company###
    #Sam Altman CEO di OpenAi gà presente come founder WorldCoin
    #CZ già presente come founder BNB
    "Tim Cook": ["tim cook"],               #apple
    "Jensen Huang": ["jensen huang"],       #nvidia
    "Michael Saylor": ["michael saylor"],   #micorstrategy
    "Brian Armstrong": ["brian armstrong"], #coinbase
    "Elon Musk": ["elon musk","musk"],      #tesla
    "Satya Nadella": ["satya nadella"],     #microsoft
    "Sundar Pichai": ["sundar pichai"],     #google
    "Andy Jassy": ["andy jassy"],           #amazon
    "Mark Zuckerberg": ["mark zuckerberg","zuckerberg"], #facebook
    "Arvind Krishna": ["arvind krishna"],   #IBM
    "Han Jong-hee": ["han jong-hee"],       #samsung
    "Pat Gelsinger": ["pat gelsinger"],     #intel
    "Michael Novogratz": ["michael novogratz"],  #galaxy digital holding
    "Fred Thiel":["fred thiel"],            #maraton digital
    "Zachary K. Bradford":["zachary k. bradford","k. bradford","zachary bradford"], #cleanspark
    "Jason Les":["jason les"],  #riot digital
    "Paul B. Prager":["paul b. praegr","paul prager"]   #wulf 
}



crypto = {
    "Bitcoin": ["btc", "bitcoin"],
    "Ethereum": ["eth", "ethereum"],
    "Tether": ["usdt", "tether"],
    "XRP": ["xrp", "ripple"],
    "BNB": ["bnb", "binance coin"],
    "Solana": ["sol", "solana"],
    "USDC": ["usdc", "usd coin"],
    "Dogecoin": ["dogecoin","doge"],
    "Cardano": ["ada", "cardano"],
    "TRON": ["trx", "tron"],
    "Chainlink": ["link", "chainlink"],
    "Toncoin": ["ton", "toncoin"],
    "Avalanche": ["avax", "avalanche"],
    "Stellar": ["xlm", "stellar"],
    "Hedera": ["hbar", "hedera", "hedera hashgraph"],
    "Shiba Inu": ["shib", "shiba inu"],
    "Sui": ["sui","sui network"],
    "Polkadot": ["dot", "polkadot"],
    "Litecoin": ["ltc", "litecoin"],
    "Pi": ["pi", "pi network"],
    "Mantra": ["mantra", "mantra dao","om"],
    "Bitget": ["bitget","bgb"],
    "Hyperliquid": ["hyperliquid"],
    "Uniswap": ["uni", "uniswap"],
    "Monero": ["xmr", "monero"],
    "Aptos": ["apt", "aptos"],
    "Near": ["near", "near protocol"],
    "Pepe": ["pepe", "pepecoin"],
    "OKB": ["okb", "okex"],
    "Aave": ["aave"],
    "Internet Computer": ["icp", "internet computer"],
    "Mantle": ["mnt","mantle"],
    "Ondo": ["ondo"],
    "Bittensor": ["tao", "bittensor"],
    "POL": ["pol", "polygon","matic"],
    "VeChain": ["vet", "vechain"],
    "Cronos": ["cro", "cronos"],
    "Ethena": ["ethena"],
    "Kaspa": ["kas", "kaspa"],
    "Celestia": ["celestia"],
    "Filecoin": ["fil", "filecoin"],
    "Gate": ["gate", "gate.io","gateToken"],
    "Render": ["rndr", "render"],
    "Cosmos": ["atom", "cosmos"],
    "Arbitrum": ["arbitrum", "arb"],
    "Algorand": ["algo", "algorand"],
    "Sonic": ["sonic","fantom","ftm"],
    "Jupiter": ["jupiter","jup"],
    "Optimism": ["op", "optimism"],
    "KuCoin": ["kcs", "kucoin"],
    "Artificial Superintelligence Alliance": ["fet", "artificial superintelligence alliance"],
    "Immutable": ["imx", "immutable"],
    "Injective": ["inj", "injective"],
    "Movement": ["movement","move"],
    "Worldcoin": ["wld", "worldcoin"],
    "Sei": ["sei"],
    "Theta Network": ["theta", "theta network"],
    "Gala": ["gala"],
    "Nexo": ["nexo"],
    "Berachain": ["berachain","bera"],
    "Raydium":["ray","raydium"],
    "Helium": ["hnt", "helium"],
    "Ronin": ["ron", "ronin"],
    "Pendle": ["pendle"],
    "Beam": ["beam"],
    "Aethir": ["aethir","ath"]
}


financial_institutions = {
    "FED": ["fed", "federal reserve", "federal reserve bank"],
    "BCE": ["bce", "banca centrale europea", "european central bank"],
    "SEC": ["sec", "securities and exchange commission", "security exchange commission"],
    "BRI": ["bri", "banca dei regolamenti internazionali", "bank for international settlements"],
    "FMI": ["fmi", "fondo monetario internazionale", "international monetary fund", "imf"],
    "BM": ["bm", "banca mondiale", "world bank"],
    "FSB": ["fsb", "consiglio per la stabilità finanziaria", "financial stability board"],
    "IIF": ["iif", "istituto della finanza internazionale", "institute of international finance"],
    "G30": ["g30", "gruppo dei trenta", "group of thirty"],
    "OMC": ["omc", "organizzazione mondiale del commercio", "wto", "world trade organization"],
    "ADB": ["adb", "banca asiatica di sviluppo", "asian development bank"],
    "AfDB": ["afdb", "banca africana di sviluppo", "african development bank"],
    "IDB": ["idb", "banca interamericana di sviluppo", "inter-american development bank"],
    "BERS": ["bers", "banca europea per la ricostruzione e lo sviluppo", "ebrd", "european bank for reconstruction and development"]
}

companies = {
    "Apple": ["apple", "aapl"],
    "Binance": ["binance"],
    "NVIDIA": ["nvidia", "nvda"],
    "MicroStrategy": ["microstrategy", "mstr"],
    "Coinbase": ["coinbase", "coin"],
    "Tesla": ["tesla", "tsla"],
    "Microsoft": ["microsoft", "msft"],
    "Google": ["google", "alphabet", "goog", "googl"],
    "Amazon": ["amazon", "amzn"],
    "Facebook": ["facebook", "meta", "meta platforms"],
    "IBM": ["ibm", "international business machines", "ibm"],
    "Samsung": ["samsung", "ssnlf", "ssnli"],
    "Intel": ["intel", "intc"],
    "Galaxy Digital Holdings": ["galaxy digital holdings", "galaxy digital", "glxy"],
    "Marathon Digital": ["marathon digital", "mara"],
    "CleanSpark": ["cleanspark", "clsk"],
    "Riot Digital": ["riot digital", "riot blockchain", "riot"],
    "Wulf": ["wulf", "wulf power", "wulf energy", "wulf"],
    "OpenAi":["openai","open ai","chatgpt"]
}


Founder_crypto = {
    "Bitcoin": "Satoshi Nakamoto",
    "Ethereum": "Vitalik Buterin",
    "Tether": ["Brock Pierce","Reeve Collins","Craig Sellars"],
    "XRP": ["Jed McCaleb","Chris Larsen"],
    "BNB": "Changpeng Zhao",
    "Solana": "Anatoly Yakovenko",
    "USDC": "Circle",
    "Dogecoin": ["Billy Markus"],
    "Cardano": "Charles Hoskinson",
    "TRON": "Justin Sun",
    "Chainlink": ["Sergey Nazarov","Steve Ellis"],
    "Toncoin": "Pavel Durov",
    "Avalanche": ["Emin Gün Sirer","Kevin Sekniqi","Ted Yin"],
    "Stellar":"Denelle Dixon",
    "Hedera":["Leemon Baird","Mance Harmon","Zenobia Godschalk"],
    "Shiba Inu":["Ryoshi"],
    "Sui": ["Mysten Labs","Evan Cheng","Sam Blackshear","Adeniyi Abiodun","George Danezis"],
    "Polkadot": "Gavin Wood",
    "Litecoin":"Charlie Lee",
    "Pi":"Nicolas Kokkalis",
    "Mantra":"John Patrick Mullin",
    "Bitget":"Gracy Chen",
    "Hyperliquid":["Jeff Yan","Iliensinc"],
    "Uniswap":"Hayden Adams",
    "Monero":"Joseph Liu",
    "Aptos":["Mo Shaikh","Avery Ching"],
    "Near":["Illia Polosukhin"],
    "Pepe":"Zachary Testa",
    "OKB": "Star Xu",
    "Aave": "Stani Kulechov",
    "Internet Computer": "Dominic Williams",
    "Mantle": "Pascal Leblanc",
    "Ondo": ["Nathan Allman","Pinku Suran"],
    "Bittensor": ["Jacob Steeves","Ala Shaabana"],
    "POL": ["Jaynti Kanani"],
    "VeChain": "Sunny Lu",
    "Cronos": ["Kris Marszalek","Rafael Melo","Gary Or","Bobby Bao"],
    "Ethena": ["Guy Young"],
    "Kaspa": "Yonatan Sompolinsky",
    "Celestia": "Mustafa Al-Bassam",
    "Filecoin":"Juan Benet",
    "Gate":"Lin Han",
    "Render": "Jules Urbach",
    "Cosmos": "Jae Kwon",
    "Arbitrum": ["Ed Felten","Steven Goldfeder","Harry Kalodner"],
    "Algorand": "Silvio Micali",
    "Sonic": "Andre Cronje",
    "Jupiter": "Meow",
    "Optimism": ["Jinglan Wang""Kevin Ho","Karl Floersch"],
    "KuCoin": "Johnny Lyu",
    "Artificial Superintelligence Alliance": ["Toby Simpson","Humayun Sheikh","Thomas Hain"],
    "Immutable": ["Robbie Ferguson","James Ferguson","Alex Connolly"],
    "Injective": "Eric Chen",
    "Movement": ["Rushi Manche","Cooper Scanlon"],
    "Worldcoin": "Sam Altman",
    "Sei": ["Dan Edlebeck","Jayendra Jog"],
    "Theta Network": "Mitch Liu's",
    "Gala": "Eric Schiermeyer",
    "Nexo": "Antoni Trenchev",
    "Berachain": "Man Bera",
    "Helium": "Amir Haleem",
    "Ronin": "Sky Mavis",
    "Pendle": "TN Lee",
    "Beam": ["Alexander Zaidelson","Alex Romanov","Amir Aaronson"],
    "Aethir": "Mark Rydo"
}

President_financial_institutions = {
    "FED":"Jerome Powell",
    "BCE":"Christine Lagarde",
    "SEC":"Gary Gensler",
    "BRI":"François Villeroy de Galhau",
    "FMI":"Kristalina Georgieva",
    "BM":"Ajay Banga",
    "FSB":"Klaas Knot",
    "IIF":"Josef Ackermann",
    "G30":"Tharman Shanmugaratnam",
    "OMC":"Ngozi Okonjo-Iweala",
    "ADB":"Masatsugu Asakawa",
    "AfDB":"Akinwumi A. Adesina",
    "IDB":"Ilan Goldfajn",
    "BERS":"Odile Renaud-Basso",
}

CEO_companies = {
    "Apple": "Tim Cook",
    "NVIDIA": "Jensen Huang",
    "MicroStrategy": "Michael Saylor",
    "Coinbase": "Brian Armstrong",
    "Tesla": "Elon Musk",
    "Microsoft": "Satya Nadella",
    "Google": "Sundar Pichai",
    "Amazon": "Andy Jassy",
    "Facebook": "Mark Zuckerberg",
    "IBM": "Arvind Krishna",
    "Samsung": "Han Jong-hee",
    "Intel": "Pat Gelsinger",
    "Galaxy Digital Holdings": "Michael Novogratz",
    "Marathon Digital": "Fred Thiel",
    "CleanSpark": "Zachary K. Bradford",
    "Riot Digital": "Jason Les",
    "Wulf": "Paul B. Prager",
    "OpenAi": "Sam Altman",
    "Binance": "Changpeng Zhao"
}
